# Generated by Django 3.2.13 on 2022-11-03 15:25

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='nostoreimg.jpg', upload_to='images/'),
        ),
    ]
